#!/bin/bash
# vars
env_group=0


runner_id="0"
min_task="0"
max_task="10"
env_group="0"
exp_set="APDPR_WITH_RANDOM"
avg_id="1"


is_in_list() {
    local var="$1"
    shift
    local list=("$@")
    for item in "${list[@]}"; do
        if [ "$var" == "$item" ]; then
            return 0
        fi
    done
    return 1
}

banned_machines=("00000" "18985" "19543" "22965" "17578" "21252" "15473" "19440" "9440" "13725" "10397" "6714")

min() {
    if [ "$1" -lt "$2" ]; then
        echo "$1"
    else
        echo "$2"
    fi
}




launched=0
while [ "$launched" != "1" ]; do
  proposed_machine_id="00000"
  export query_result=$(vastai search offers 'reliability > 0.99 dph < 0.3 cpu_cores_effective > 11 cpu_cores < 39 rented=False cpu_ghz > 3.4' -o 'cpu_cores_effective-' -d)

  row_n=2
  while is_in_list "$proposed_machine_id" "${banned_machines[@]}"; do
    proposed_machine_id=$(echo "$query_result" | awk "NR==$row_n"' {print $19}')

    echo "Price: "
    echo $(echo "$query_result" | awk "NR==$row_n"' {print $10}')
    echo "Id: "
    export I_ID=$(echo "$query_result" | awk "NR==$row_n"' {print $1}')
    echo "$I_ID"

    if is_in_list "$proposed_machine_id" "${banned_machines[@]}"; then
      echo "Catched bad instance incrementing $row_n $proposed_machine_id"
      row_n=$((row_n+1))
    fi
  done







  echo "Launching instance $runner_id, $avg_id, $min_task, $max_task"
  result=$(vastai create instance "$I_ID" --image pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel --disk 40 --ssh --direct --env "-e MY_RUNNER_ID=$runner_id -e MIN_TASK=$min_task -e MAX_TASK=$max_task -e ENV_GROUP=$env_group -e EXP_SET=$exp_set -e AVG_ID=$avg_id" --onstart-cmd "env | grep _ >> /etc/environment; wget https://raw.githubusercontent.com/Fotoblysk/avg-transfer-rl/master/cloud_startup.sh; chmod a+x cloud_startup.sh; bash cloud_startup.sh;";)
  echo "$result"
  launched=$(echo $result | grep "'success': True" | wc -l)
  echo "Launched: $launched"
  if [ "$launched" != "1" ]; then
    sleep 300
  fi
  sleep 1
done

echo "Launched"
