#!/bin/bash

env_group=0
exp_set=0

min() {
    if [ "$1" -lt "$2" ]; then
        echo "$1"
    else
        echo "$2"
    fi
}

tasks_per_instance=2
TASKS_NUMBER=14

max_runner_id=$((TASKS_NUMBER / tasks_per_instance))

echo $max_runner_id
AVG_MAX=2
for ((avg_id=0; avg_id<AVG_MAX; avg_id++)); do
  for ((runner_id=0; runner_id<=max_runner_id; runner_id++)); do
    launched=0
    while [ "$launched" != "1" ]; do
      export query_result=$(vastai search offers 'reliability > 0.98 dph < 0.2 cpu_cores > 1' -o 'dph+' -d)
      echo "Price: "
      echo $(echo "$query_result" | awk 'NR==2 {print $10}')
      echo "Id: "
      export I_ID=$(echo "$query_result" | awk 'NR==2 {print $1}')
      echo "$I_ID"





      min_task=$((tasks_per_instance * runner_id))
      max_task=$(((1+runner_id) * tasks_per_instance))

      max_task=$(min "$TASKS_NUMBER" "$max_task")
      if [ "$min_task" != "$max_task" ]; then
        echo "Launching instance $runner_id, $avg_id, $min_task, $max_task"
        result=$(vastai create instance "$I_ID" --image pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel --disk 16 --ssh --direct --env "-e MY_RUNNER_ID=$runner_id -e MIN_TASK=$min_task -e MAX_TASK=$max_task -e ENV_GROUP=$env_group -e EXP_SET=$exp_set -e AVG_ID=$avg_id" --onstart-cmd "env | grep _ >> /etc/environment; wget https://raw.githubusercontent.com/Fotoblysk/avg-transfer-rl/cloud_sync/cloud_startup.sh; chmod a+x cloud_startup.sh; bash cloud_startup.sh;";)
        echo "$result"
        launched=$(echo $result | grep "'success': True" | wc -l)
        echo "Launched: $launched"
      fi
      sleep 1
    done
  done
done

echo "Launched"
