#!/bin/bash
not_all_done="1"

while [ "$not_all_done" != "0" ]; do
  echo 'Periodic check for done instances'
  not_all_done="0"
  export INSTANCES_RAW=$(vastai show instances)
  instances_n=$(echo "$INSTANCES_RAW" | wc -l)
  for i in $(seq 2 $instances_n)
  do
    echo "Current number: $i"
    instance_id=$(echo "$INSTANCES_RAW" | awk 'NR=='"$i"' {print $1}')
    echo "Instance id: $instance_id"
    ssh_url=$(vastai ssh-url "$instance_id")

    is_done=$(ssh -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey "$ssh_url" "ls | grep jobs_done | wc -l")
    runner_id=$(ssh -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey "$ssh_url" 'echo $MY_RUNNER_ID')
    exp_set=$(ssh -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey "$ssh_url" 'echo $EXP_SET')
    avg_id=$(ssh -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey "$ssh_url" 'echo $AVG_ID')
    env_group=$(ssh -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey "$ssh_url" 'echo $ENV_GROUP')

    echo "IS_DONE"
    echo "$is_done"
    if [ "$is_done" == "1" ]; then
      mkdir -p "cloud_results/$runner_id"

      user=$(echo $ssh_url | awk -F'[/:@]' '{print $4}')
      host=$(echo $ssh_url | awk -F'[/:@]' '{print $5}')
      port=$(echo $ssh_url | awk -F'[/:@]' '{print $6}')

      scp -o "StrictHostKeyChecking no" -i ~/vast_tmp/sshkey -P "$port" "$user@$host:/root/results.tar.gz" "./cloud_results/$exp_set-$env_group-$avg_id/$runner_id"
      echo "Done removing instance"
      vastai destroy instance "$instance_id"
    else
      echo "Not done yet"
      not_all_done=is_done
    fi
  done
  echo "Loop check end"
  sleep 300
done
